/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellSplatRouteImport } from './routes/_shell/$'
import { Route as ShellCheckInRouteImport } from './routes/_shell/check-in'
import { Route as ShellConnectionsRouteImport } from './routes/_shell/connections'
import { Route as ShellIntakeRouteImport } from './routes/_shell/intake'
import { Route as ShellNotificationsRouteImport } from './routes/_shell/notifications'
import { Route as ShellRunsRouteImport } from './routes/_shell/runs'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellWorkflowsRouteImport } from './routes/_shell/workflows'
import { Route as OnboardingTimezoneRouteImport } from './routes/onboarding/timezone'
import { Route as ShellFleetIndexRouteImport } from './routes/_shell/fleet/index'
import { Route as ShellFleetRunnerIdRouteImport } from './routes/_shell/fleet/$runnerId'
import { Route as ShellSessionsIndexRouteImport } from './routes/_shell/sessions/index'
import { Route as ShellSettingsIndexRouteImport } from './routes/_shell/settings/index'
import { Route as ShellSettingsAssistantsRouteImport } from './routes/_shell/settings/assistants'
import { Route as ShellSettingsBoundsRouteImport } from './routes/_shell/settings/bounds'
import { Route as ShellSettingsIdentitiesRouteImport } from './routes/_shell/settings/identities'
import { Route as ShellSettingsPermissionProfilesRouteImport } from './routes/_shell/settings/permission-profiles'
import { Route as ShellSettingsPluginsRouteImport } from './routes/_shell/settings/plugins'
import { Route as ShellSettingsProfileRouteImport } from './routes/_shell/settings/profile'
import { Route as ShellSettingsSecretsRouteImport } from './routes/_shell/settings/secrets'
import { Route as ShellSettingsSystemRouteImport } from './routes/_shell/settings/system'
import { Route as ShellSettingsThreadsRouteImport } from './routes/_shell/settings/threads'
import { Route as ShellTasksIndexRouteImport } from './routes/_shell/tasks/index'
import { Route as ShellThreadsSessionIdRouteImport } from './routes/_shell/threads/$sessionId'
import { Route as ShellThreadsNewRouteImport } from './routes/_shell/threads/new'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSplatRoute = ShellSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCheckInRoute = ShellCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConnectionsRoute = ShellConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIntakeRoute = ShellIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRunsRoute = ShellRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWorkflowsRoute = ShellWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => ShellRoute,
} as any)
const OnboardingTimezoneRoute = OnboardingTimezoneRouteImport.update({
  id: '/onboarding/timezone',
  path: '/onboarding/timezone',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellFleetIndexRoute = ShellFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFleetRunnerIdRoute = ShellFleetRunnerIdRouteImport.update({
  id: '/fleet/$runnerId',
  path: '/fleet/$runnerId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSessionsIndexRoute = ShellSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsIndexRoute = ShellSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsAssistantsRoute = ShellSettingsAssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsBoundsRoute = ShellSettingsBoundsRouteImport.update({
  id: '/bounds',
  path: '/bounds',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsIdentitiesRoute = ShellSettingsIdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsPermissionProfilesRoute =
  ShellSettingsPermissionProfilesRouteImport.update({
    id: '/permission-profiles',
    path: '/permission-profiles',
    getParentRoute: () => ShellSettingsRoute,
  } as any)
const ShellSettingsPluginsRoute = ShellSettingsPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsProfileRoute = ShellSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsSecretsRoute = ShellSettingsSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsSystemRoute = ShellSettingsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellSettingsThreadsRoute = ShellSettingsThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => ShellSettingsRoute,
} as any)
const ShellTasksIndexRoute = ShellTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellThreadsSessionIdRoute = ShellThreadsSessionIdRouteImport.update({
  id: '/threads/$sessionId',
  path: '/threads/$sessionId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellThreadsNewRoute = ShellThreadsNewRouteImport.update({
  id: '/threads/new',
  path: '/threads/new',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/$': typeof ShellSplatRoute
  '/check-in': typeof ShellCheckInRoute
  '/connections': typeof ShellConnectionsRoute
  '/intake': typeof ShellIntakeRoute
  '/notifications': typeof ShellNotificationsRoute
  '/runs': typeof ShellRunsRoute
  '/settings': typeof ShellSettingsRouteWithChildren
  '/workflows': typeof ShellWorkflowsRoute
  '/onboarding/timezone': typeof OnboardingTimezoneRoute
  '/fleet/$runnerId': typeof ShellFleetRunnerIdRoute
  '/settings/assistants': typeof ShellSettingsAssistantsRoute
  '/settings/bounds': typeof ShellSettingsBoundsRoute
  '/settings/identities': typeof ShellSettingsIdentitiesRoute
  '/settings/permission-profiles': typeof ShellSettingsPermissionProfilesRoute
  '/settings/plugins': typeof ShellSettingsPluginsRoute
  '/settings/profile': typeof ShellSettingsProfileRoute
  '/settings/secrets': typeof ShellSettingsSecretsRoute
  '/settings/system': typeof ShellSettingsSystemRoute
  '/settings/threads': typeof ShellSettingsThreadsRoute
  '/threads/$sessionId': typeof ShellThreadsSessionIdRoute
  '/threads/new': typeof ShellThreadsNewRoute
  '/fleet/': typeof ShellFleetIndexRoute
  '/sessions/': typeof ShellSessionsIndexRoute
  '/settings/': typeof ShellSettingsIndexRoute
  '/tasks/': typeof ShellTasksIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/$': typeof ShellSplatRoute
  '/check-in': typeof ShellCheckInRoute
  '/connections': typeof ShellConnectionsRoute
  '/intake': typeof ShellIntakeRoute
  '/notifications': typeof ShellNotificationsRoute
  '/runs': typeof ShellRunsRoute
  '/workflows': typeof ShellWorkflowsRoute
  '/onboarding/timezone': typeof OnboardingTimezoneRoute
  '/': typeof ShellIndexRoute
  '/fleet/$runnerId': typeof ShellFleetRunnerIdRoute
  '/settings/assistants': typeof ShellSettingsAssistantsRoute
  '/settings/bounds': typeof ShellSettingsBoundsRoute
  '/settings/identities': typeof ShellSettingsIdentitiesRoute
  '/settings/permission-profiles': typeof ShellSettingsPermissionProfilesRoute
  '/settings/plugins': typeof ShellSettingsPluginsRoute
  '/settings/profile': typeof ShellSettingsProfileRoute
  '/settings/secrets': typeof ShellSettingsSecretsRoute
  '/settings/system': typeof ShellSettingsSystemRoute
  '/settings/threads': typeof ShellSettingsThreadsRoute
  '/threads/$sessionId': typeof ShellThreadsSessionIdRoute
  '/threads/new': typeof ShellThreadsNewRoute
  '/fleet': typeof ShellFleetIndexRoute
  '/sessions': typeof ShellSessionsIndexRoute
  '/settings': typeof ShellSettingsIndexRoute
  '/tasks': typeof ShellTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_shell/$': typeof ShellSplatRoute
  '/_shell/check-in': typeof ShellCheckInRoute
  '/_shell/connections': typeof ShellConnectionsRoute
  '/_shell/intake': typeof ShellIntakeRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/runs': typeof ShellRunsRoute
  '/_shell/settings': typeof ShellSettingsRouteWithChildren
  '/_shell/workflows': typeof ShellWorkflowsRoute
  '/onboarding/timezone': typeof OnboardingTimezoneRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/fleet/$runnerId': typeof ShellFleetRunnerIdRoute
  '/_shell/settings/assistants': typeof ShellSettingsAssistantsRoute
  '/_shell/settings/bounds': typeof ShellSettingsBoundsRoute
  '/_shell/settings/identities': typeof ShellSettingsIdentitiesRoute
  '/_shell/settings/permission-profiles': typeof ShellSettingsPermissionProfilesRoute
  '/_shell/settings/plugins': typeof ShellSettingsPluginsRoute
  '/_shell/settings/profile': typeof ShellSettingsProfileRoute
  '/_shell/settings/secrets': typeof ShellSettingsSecretsRoute
  '/_shell/settings/system': typeof ShellSettingsSystemRoute
  '/_shell/settings/threads': typeof ShellSettingsThreadsRoute
  '/_shell/threads/$sessionId': typeof ShellThreadsSessionIdRoute
  '/_shell/threads/new': typeof ShellThreadsNewRoute
  '/_shell/fleet/': typeof ShellFleetIndexRoute
  '/_shell/sessions/': typeof ShellSessionsIndexRoute
  '/_shell/settings/': typeof ShellSettingsIndexRoute
  '/_shell/tasks/': typeof ShellTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/$'
    | '/check-in'
    | '/connections'
    | '/intake'
    | '/notifications'
    | '/runs'
    | '/settings'
    | '/workflows'
    | '/onboarding/timezone'
    | '/fleet/$runnerId'
    | '/settings/assistants'
    | '/settings/bounds'
    | '/settings/identities'
    | '/settings/permission-profiles'
    | '/settings/plugins'
    | '/settings/profile'
    | '/settings/secrets'
    | '/settings/system'
    | '/settings/threads'
    | '/threads/$sessionId'
    | '/threads/new'
    | '/fleet/'
    | '/sessions/'
    | '/settings/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/$'
    | '/check-in'
    | '/connections'
    | '/intake'
    | '/notifications'
    | '/runs'
    | '/workflows'
    | '/onboarding/timezone'
    | '/'
    | '/fleet/$runnerId'
    | '/settings/assistants'
    | '/settings/bounds'
    | '/settings/identities'
    | '/settings/permission-profiles'
    | '/settings/plugins'
    | '/settings/profile'
    | '/settings/secrets'
    | '/settings/system'
    | '/settings/threads'
    | '/threads/$sessionId'
    | '/threads/new'
    | '/fleet'
    | '/sessions'
    | '/settings'
    | '/tasks'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/setup'
    | '/_shell/$'
    | '/_shell/check-in'
    | '/_shell/connections'
    | '/_shell/intake'
    | '/_shell/notifications'
    | '/_shell/runs'
    | '/_shell/settings'
    | '/_shell/workflows'
    | '/onboarding/timezone'
    | '/_shell/'
    | '/_shell/fleet/$runnerId'
    | '/_shell/settings/assistants'
    | '/_shell/settings/bounds'
    | '/_shell/settings/identities'
    | '/_shell/settings/permission-profiles'
    | '/_shell/settings/plugins'
    | '/_shell/settings/profile'
    | '/_shell/settings/secrets'
    | '/_shell/settings/system'
    | '/_shell/settings/threads'
    | '/_shell/threads/$sessionId'
    | '/_shell/threads/new'
    | '/_shell/fleet/'
    | '/_shell/sessions/'
    | '/_shell/settings/'
    | '/_shell/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  OnboardingTimezoneRoute: typeof OnboardingTimezoneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/$': {
      id: '/_shell/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof ShellSplatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/check-in': {
      id: '/_shell/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof ShellCheckInRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/connections': {
      id: '/_shell/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ShellConnectionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/intake': {
      id: '/_shell/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof ShellIntakeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/runs': {
      id: '/_shell/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof ShellRunsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/workflows': {
      id: '/_shell/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof ShellWorkflowsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/onboarding/timezone': {
      id: '/onboarding/timezone'
      path: '/onboarding/timezone'
      fullPath: '/onboarding/timezone'
      preLoaderRoute: typeof OnboardingTimezoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/fleet/': {
      id: '/_shell/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof ShellFleetIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/fleet/$runnerId': {
      id: '/_shell/fleet/$runnerId'
      path: '/fleet/$runnerId'
      fullPath: '/fleet/$runnerId'
      preLoaderRoute: typeof ShellFleetRunnerIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sessions/': {
      id: '/_shell/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof ShellSessionsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings/': {
      id: '/_shell/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ShellSettingsIndexRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/assistants': {
      id: '/_shell/settings/assistants'
      path: '/assistants'
      fullPath: '/settings/assistants'
      preLoaderRoute: typeof ShellSettingsAssistantsRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/bounds': {
      id: '/_shell/settings/bounds'
      path: '/bounds'
      fullPath: '/settings/bounds'
      preLoaderRoute: typeof ShellSettingsBoundsRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/identities': {
      id: '/_shell/settings/identities'
      path: '/identities'
      fullPath: '/settings/identities'
      preLoaderRoute: typeof ShellSettingsIdentitiesRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/permission-profiles': {
      id: '/_shell/settings/permission-profiles'
      path: '/permission-profiles'
      fullPath: '/settings/permission-profiles'
      preLoaderRoute: typeof ShellSettingsPermissionProfilesRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/plugins': {
      id: '/_shell/settings/plugins'
      path: '/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof ShellSettingsPluginsRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/profile': {
      id: '/_shell/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ShellSettingsProfileRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/secrets': {
      id: '/_shell/settings/secrets'
      path: '/secrets'
      fullPath: '/settings/secrets'
      preLoaderRoute: typeof ShellSettingsSecretsRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/system': {
      id: '/_shell/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof ShellSettingsSystemRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/settings/threads': {
      id: '/_shell/settings/threads'
      path: '/threads'
      fullPath: '/settings/threads'
      preLoaderRoute: typeof ShellSettingsThreadsRouteImport
      parentRoute: typeof ShellSettingsRoute
    }
    '/_shell/tasks/': {
      id: '/_shell/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof ShellTasksIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/threads/$sessionId': {
      id: '/_shell/threads/$sessionId'
      path: '/threads/$sessionId'
      fullPath: '/threads/$sessionId'
      preLoaderRoute: typeof ShellThreadsSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/threads/new': {
      id: '/_shell/threads/new'
      path: '/threads/new'
      fullPath: '/threads/new'
      preLoaderRoute: typeof ShellThreadsNewRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellSettingsRouteChildren {
  ShellSettingsAssistantsRoute: typeof ShellSettingsAssistantsRoute
  ShellSettingsBoundsRoute: typeof ShellSettingsBoundsRoute
  ShellSettingsIdentitiesRoute: typeof ShellSettingsIdentitiesRoute
  ShellSettingsPermissionProfilesRoute: typeof ShellSettingsPermissionProfilesRoute
  ShellSettingsPluginsRoute: typeof ShellSettingsPluginsRoute
  ShellSettingsProfileRoute: typeof ShellSettingsProfileRoute
  ShellSettingsSecretsRoute: typeof ShellSettingsSecretsRoute
  ShellSettingsSystemRoute: typeof ShellSettingsSystemRoute
  ShellSettingsThreadsRoute: typeof ShellSettingsThreadsRoute
  ShellSettingsIndexRoute: typeof ShellSettingsIndexRoute
}

const ShellSettingsRouteChildren: ShellSettingsRouteChildren = {
  ShellSettingsAssistantsRoute: ShellSettingsAssistantsRoute,
  ShellSettingsBoundsRoute: ShellSettingsBoundsRoute,
  ShellSettingsIdentitiesRoute: ShellSettingsIdentitiesRoute,
  ShellSettingsPermissionProfilesRoute: ShellSettingsPermissionProfilesRoute,
  ShellSettingsPluginsRoute: ShellSettingsPluginsRoute,
  ShellSettingsProfileRoute: ShellSettingsProfileRoute,
  ShellSettingsSecretsRoute: ShellSettingsSecretsRoute,
  ShellSettingsSystemRoute: ShellSettingsSystemRoute,
  ShellSettingsThreadsRoute: ShellSettingsThreadsRoute,
  ShellSettingsIndexRoute: ShellSettingsIndexRoute,
}

const ShellSettingsRouteWithChildren = ShellSettingsRoute._addFileChildren(
  ShellSettingsRouteChildren,
)

interface ShellRouteChildren {
  ShellSplatRoute: typeof ShellSplatRoute
  ShellCheckInRoute: typeof ShellCheckInRoute
  ShellConnectionsRoute: typeof ShellConnectionsRoute
  ShellIntakeRoute: typeof ShellIntakeRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellRunsRoute: typeof ShellRunsRoute
  ShellSettingsRoute: typeof ShellSettingsRouteWithChildren
  ShellWorkflowsRoute: typeof ShellWorkflowsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellFleetRunnerIdRoute: typeof ShellFleetRunnerIdRoute
  ShellThreadsSessionIdRoute: typeof ShellThreadsSessionIdRoute
  ShellThreadsNewRoute: typeof ShellThreadsNewRoute
  ShellFleetIndexRoute: typeof ShellFleetIndexRoute
  ShellSessionsIndexRoute: typeof ShellSessionsIndexRoute
  ShellTasksIndexRoute: typeof ShellTasksIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellSplatRoute: ShellSplatRoute,
  ShellCheckInRoute: ShellCheckInRoute,
  ShellConnectionsRoute: ShellConnectionsRoute,
  ShellIntakeRoute: ShellIntakeRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellRunsRoute: ShellRunsRoute,
  ShellSettingsRoute: ShellSettingsRouteWithChildren,
  ShellWorkflowsRoute: ShellWorkflowsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellFleetRunnerIdRoute: ShellFleetRunnerIdRoute,
  ShellThreadsSessionIdRoute: ShellThreadsSessionIdRoute,
  ShellThreadsNewRoute: ShellThreadsNewRoute,
  ShellFleetIndexRoute: ShellFleetIndexRoute,
  ShellSessionsIndexRoute: ShellSessionsIndexRoute,
  ShellTasksIndexRoute: ShellTasksIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  OnboardingTimezoneRoute: OnboardingTimezoneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
