/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as OnboardingTimezoneRouteImport } from './routes/onboarding/timezone'
import { Route as SettingsAssistantsRouteImport } from './routes/settings/assistants'
import { Route as SettingsBoundsRouteImport } from './routes/settings/bounds'
import { Route as SettingsIdentitiesRouteImport } from './routes/settings/identities'
import { Route as SettingsPermissionProfilesRouteImport } from './routes/settings/permission-profiles'
import { Route as SettingsPluginsRouteImport } from './routes/settings/plugins'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsSecretsRouteImport } from './routes/settings/secrets'
import { Route as SettingsSystemRouteImport } from './routes/settings/system'
import { Route as SettingsThreadsRouteImport } from './routes/settings/threads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTimezoneRoute = OnboardingTimezoneRouteImport.update({
  id: '/onboarding/timezone',
  path: '/onboarding/timezone',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAssistantsRoute = SettingsAssistantsRouteImport.update({
  id: '/settings/assistants',
  path: '/settings/assistants',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBoundsRoute = SettingsBoundsRouteImport.update({
  id: '/settings/bounds',
  path: '/settings/bounds',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIdentitiesRoute = SettingsIdentitiesRouteImport.update({
  id: '/settings/identities',
  path: '/settings/identities',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPermissionProfilesRoute =
  SettingsPermissionProfilesRouteImport.update({
    id: '/settings/permission-profiles',
    path: '/settings/permission-profiles',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsPluginsRoute = SettingsPluginsRouteImport.update({
  id: '/settings/plugins',
  path: '/settings/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecretsRoute = SettingsSecretsRouteImport.update({
  id: '/settings/secrets',
  path: '/settings/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThreadsRoute = SettingsThreadsRouteImport.update({
  id: '/settings/threads',
  path: '/settings/threads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/connections': typeof ConnectionsRoute
  '/fleet': typeof FleetRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/runs': typeof RunsRoute
  '/setup': typeof SetupRoute
  '/tasks': typeof TasksRoute
  '/workflows': typeof WorkflowsRoute
  '/onboarding/timezone': typeof OnboardingTimezoneRoute
  '/settings/assistants': typeof SettingsAssistantsRoute
  '/settings/bounds': typeof SettingsBoundsRoute
  '/settings/identities': typeof SettingsIdentitiesRoute
  '/settings/permission-profiles': typeof SettingsPermissionProfilesRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/secrets': typeof SettingsSecretsRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/threads': typeof SettingsThreadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/connections': typeof ConnectionsRoute
  '/fleet': typeof FleetRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/runs': typeof RunsRoute
  '/setup': typeof SetupRoute
  '/tasks': typeof TasksRoute
  '/workflows': typeof WorkflowsRoute
  '/onboarding/timezone': typeof OnboardingTimezoneRoute
  '/settings/assistants': typeof SettingsAssistantsRoute
  '/settings/bounds': typeof SettingsBoundsRoute
  '/settings/identities': typeof SettingsIdentitiesRoute
  '/settings/permission-profiles': typeof SettingsPermissionProfilesRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/secrets': typeof SettingsSecretsRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/threads': typeof SettingsThreadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/connections': typeof ConnectionsRoute
  '/fleet': typeof FleetRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/runs': typeof RunsRoute
  '/setup': typeof SetupRoute
  '/tasks': typeof TasksRoute
  '/workflows': typeof WorkflowsRoute
  '/onboarding/timezone': typeof OnboardingTimezoneRoute
  '/settings/assistants': typeof SettingsAssistantsRoute
  '/settings/bounds': typeof SettingsBoundsRoute
  '/settings/identities': typeof SettingsIdentitiesRoute
  '/settings/permission-profiles': typeof SettingsPermissionProfilesRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/secrets': typeof SettingsSecretsRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/threads': typeof SettingsThreadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in'
    | '/connections'
    | '/fleet'
    | '/intake'
    | '/login'
    | '/notifications'
    | '/runs'
    | '/setup'
    | '/tasks'
    | '/workflows'
    | '/onboarding/timezone'
    | '/settings/assistants'
    | '/settings/bounds'
    | '/settings/identities'
    | '/settings/permission-profiles'
    | '/settings/plugins'
    | '/settings/profile'
    | '/settings/secrets'
    | '/settings/system'
    | '/settings/threads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/connections'
    | '/fleet'
    | '/intake'
    | '/login'
    | '/notifications'
    | '/runs'
    | '/setup'
    | '/tasks'
    | '/workflows'
    | '/onboarding/timezone'
    | '/settings/assistants'
    | '/settings/bounds'
    | '/settings/identities'
    | '/settings/permission-profiles'
    | '/settings/plugins'
    | '/settings/profile'
    | '/settings/secrets'
    | '/settings/system'
    | '/settings/threads'
  id:
    | '__root__'
    | '/'
    | '/check-in'
    | '/connections'
    | '/fleet'
    | '/intake'
    | '/login'
    | '/notifications'
    | '/runs'
    | '/setup'
    | '/tasks'
    | '/workflows'
    | '/onboarding/timezone'
    | '/settings/assistants'
    | '/settings/bounds'
    | '/settings/identities'
    | '/settings/permission-profiles'
    | '/settings/plugins'
    | '/settings/profile'
    | '/settings/secrets'
    | '/settings/system'
    | '/settings/threads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInRoute: typeof CheckInRoute
  ConnectionsRoute: typeof ConnectionsRoute
  FleetRoute: typeof FleetRoute
  IntakeRoute: typeof IntakeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RunsRoute: typeof RunsRoute
  SetupRoute: typeof SetupRoute
  TasksRoute: typeof TasksRoute
  WorkflowsRoute: typeof WorkflowsRoute
  OnboardingTimezoneRoute: typeof OnboardingTimezoneRoute
  SettingsAssistantsRoute: typeof SettingsAssistantsRoute
  SettingsBoundsRoute: typeof SettingsBoundsRoute
  SettingsIdentitiesRoute: typeof SettingsIdentitiesRoute
  SettingsPermissionProfilesRoute: typeof SettingsPermissionProfilesRoute
  SettingsPluginsRoute: typeof SettingsPluginsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecretsRoute: typeof SettingsSecretsRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsThreadsRoute: typeof SettingsThreadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/timezone': {
      id: '/onboarding/timezone'
      path: '/onboarding/timezone'
      fullPath: '/onboarding/timezone'
      preLoaderRoute: typeof OnboardingTimezoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/assistants': {
      id: '/settings/assistants'
      path: '/settings/assistants'
      fullPath: '/settings/assistants'
      preLoaderRoute: typeof SettingsAssistantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/bounds': {
      id: '/settings/bounds'
      path: '/settings/bounds'
      fullPath: '/settings/bounds'
      preLoaderRoute: typeof SettingsBoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/identities': {
      id: '/settings/identities'
      path: '/settings/identities'
      fullPath: '/settings/identities'
      preLoaderRoute: typeof SettingsIdentitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/permission-profiles': {
      id: '/settings/permission-profiles'
      path: '/settings/permission-profiles'
      fullPath: '/settings/permission-profiles'
      preLoaderRoute: typeof SettingsPermissionProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/plugins': {
      id: '/settings/plugins'
      path: '/settings/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof SettingsPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/secrets': {
      id: '/settings/secrets'
      path: '/settings/secrets'
      fullPath: '/settings/secrets'
      preLoaderRoute: typeof SettingsSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/threads': {
      id: '/settings/threads'
      path: '/settings/threads'
      fullPath: '/settings/threads'
      preLoaderRoute: typeof SettingsThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInRoute: CheckInRoute,
  ConnectionsRoute: ConnectionsRoute,
  FleetRoute: FleetRoute,
  IntakeRoute: IntakeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RunsRoute: RunsRoute,
  SetupRoute: SetupRoute,
  TasksRoute: TasksRoute,
  WorkflowsRoute: WorkflowsRoute,
  OnboardingTimezoneRoute: OnboardingTimezoneRoute,
  SettingsAssistantsRoute: SettingsAssistantsRoute,
  SettingsBoundsRoute: SettingsBoundsRoute,
  SettingsIdentitiesRoute: SettingsIdentitiesRoute,
  SettingsPermissionProfilesRoute: SettingsPermissionProfilesRoute,
  SettingsPluginsRoute: SettingsPluginsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecretsRoute: SettingsSecretsRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsThreadsRoute: SettingsThreadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
