/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectedRouteImport } from './routes/_connected'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ConnectedShellRouteImport } from './routes/_connected/_shell'
import { Route as ConnectedLoginRouteImport } from './routes/_connected/login'
import { Route as ConnectedShellIndexRouteImport } from './routes/_connected/_shell/index'

const ConnectedRoute = ConnectedRouteImport.update({
  id: '/_connected',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectedShellRoute = ConnectedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => ConnectedRoute,
} as any)
const ConnectedLoginRoute = ConnectedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ConnectedRoute,
} as any)
const ConnectedShellIndexRoute = ConnectedShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectedShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ConnectedShellIndexRoute
  '/connect': typeof ConnectRoute
  '/login': typeof ConnectedLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof ConnectedShellIndexRoute
  '/connect': typeof ConnectRoute
  '/login': typeof ConnectedLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_connected': typeof ConnectedRouteWithChildren
  '/connect': typeof ConnectRoute
  '/_connected/_shell': typeof ConnectedShellRouteWithChildren
  '/_connected/login': typeof ConnectedLoginRoute
  '/_connected/_shell/': typeof ConnectedShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connect' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connect' | '/login'
  id:
    | '__root__'
    | '/_connected'
    | '/connect'
    | '/_connected/_shell'
    | '/_connected/login'
    | '/_connected/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConnectedRoute: typeof ConnectedRouteWithChildren
  ConnectRoute: typeof ConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_connected': {
      id: '/_connected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConnectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_connected/_shell': {
      id: '/_connected/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConnectedShellRouteImport
      parentRoute: typeof ConnectedRoute
    }
    '/_connected/login': {
      id: '/_connected/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ConnectedLoginRouteImport
      parentRoute: typeof ConnectedRoute
    }
    '/_connected/_shell/': {
      id: '/_connected/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConnectedShellIndexRouteImport
      parentRoute: typeof ConnectedShellRoute
    }
  }
}

interface ConnectedShellRouteChildren {
  ConnectedShellIndexRoute: typeof ConnectedShellIndexRoute
}

const ConnectedShellRouteChildren: ConnectedShellRouteChildren = {
  ConnectedShellIndexRoute: ConnectedShellIndexRoute,
}

const ConnectedShellRouteWithChildren = ConnectedShellRoute._addFileChildren(
  ConnectedShellRouteChildren,
)

interface ConnectedRouteChildren {
  ConnectedShellRoute: typeof ConnectedShellRouteWithChildren
  ConnectedLoginRoute: typeof ConnectedLoginRoute
}

const ConnectedRouteChildren: ConnectedRouteChildren = {
  ConnectedShellRoute: ConnectedShellRouteWithChildren,
  ConnectedLoginRoute: ConnectedLoginRoute,
}

const ConnectedRouteWithChildren = ConnectedRoute._addFileChildren(
  ConnectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ConnectedRoute: ConnectedRouteWithChildren,
  ConnectRoute: ConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
