/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectedRouteImport } from './routes/_connected'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as FirstRunRouteRouteImport } from './routes/first-run/route'
import { Route as ConnectedShellRouteImport } from './routes/_connected/_shell'
import { Route as ConnectedLoginRouteImport } from './routes/_connected/login'
import { Route as ConnectedShellIndexRouteImport } from './routes/_connected/_shell/index'
import { Route as ConnectedShellOfficeRouteImport } from './routes/_connected/_shell/office'
import { Route as ConnectedShellSettingsRouteRouteImport } from './routes/_connected/_shell/settings/route'
import { Route as ConnectedShellWorkflowsRouteRouteImport } from './routes/_connected/_shell/workflows/route'
import { Route as ConnectedShellAssistantsAssistantIdRouteImport } from './routes/_connected/_shell/assistants/$assistantId'
import { Route as ConnectedShellSettingsIndexRouteImport } from './routes/_connected/_shell/settings/index'
import { Route as ConnectedShellSettingsAppearanceRouteImport } from './routes/_connected/_shell/settings/appearance'
import { Route as ConnectedShellSettingsAssistantsRouteRouteImport } from './routes/_connected/_shell/settings/assistants/route'
import { Route as ConnectedShellSettingsProfileRouteImport } from './routes/_connected/_shell/settings/profile'
import { Route as ConnectedShellSettingsSystemRouteImport } from './routes/_connected/_shell/settings/system'
import { Route as ConnectedShellThreadsSessionIdRouteRouteImport } from './routes/_connected/_shell/threads/$sessionId/route'
import { Route as ConnectedShellWorkflowsWorkflowIdRouteImport } from './routes/_connected/_shell/workflows/$workflowId'
import { Route as ConnectedShellSettingsPermissionProfilesIndexRouteImport } from './routes/_connected/_shell/settings/permission-profiles/index'
import { Route as ConnectedShellSettingsPermissionProfilesIdRouteImport } from './routes/_connected/_shell/settings/permission-profiles/$id'
import { Route as ConnectedShellThreadsSessionIdIndexRouteImport } from './routes/_connected/_shell/threads/$sessionId/index'
import { Route as ConnectedShellThreadsSessionIdSubagentsSubagentIdRouteImport } from './routes/_connected/_shell/threads/$sessionId/subagents/$subagentId'

const ConnectedRoute = ConnectedRouteImport.update({
  id: '/_connected',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstRunRouteRoute = FirstRunRouteRouteImport.update({
  id: '/first-run',
  path: '/first-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectedShellRoute = ConnectedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => ConnectedRoute,
} as any)
const ConnectedLoginRoute = ConnectedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ConnectedRoute,
} as any)
const ConnectedShellIndexRoute = ConnectedShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectedShellRoute,
} as any)
const ConnectedShellOfficeRoute = ConnectedShellOfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => ConnectedShellRoute,
} as any)
const ConnectedShellSettingsRouteRoute =
  ConnectedShellSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ConnectedShellRoute,
  } as any)
const ConnectedShellWorkflowsRouteRoute =
  ConnectedShellWorkflowsRouteRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => ConnectedShellRoute,
  } as any)
const ConnectedShellAssistantsAssistantIdRoute =
  ConnectedShellAssistantsAssistantIdRouteImport.update({
    id: '/assistants/$assistantId',
    path: '/assistants/$assistantId',
    getParentRoute: () => ConnectedShellRoute,
  } as any)
const ConnectedShellSettingsIndexRoute =
  ConnectedShellSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnectedShellSettingsRouteRoute,
  } as any)
const ConnectedShellSettingsAppearanceRoute =
  ConnectedShellSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => ConnectedShellSettingsRouteRoute,
  } as any)
const ConnectedShellSettingsAssistantsRouteRoute =
  ConnectedShellSettingsAssistantsRouteRouteImport.update({
    id: '/assistants',
    path: '/assistants',
    getParentRoute: () => ConnectedShellSettingsRouteRoute,
  } as any)
const ConnectedShellSettingsProfileRoute =
  ConnectedShellSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ConnectedShellSettingsRouteRoute,
  } as any)
const ConnectedShellSettingsSystemRoute =
  ConnectedShellSettingsSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => ConnectedShellSettingsRouteRoute,
  } as any)
const ConnectedShellThreadsSessionIdRouteRoute =
  ConnectedShellThreadsSessionIdRouteRouteImport.update({
    id: '/threads/$sessionId',
    path: '/threads/$sessionId',
    getParentRoute: () => ConnectedShellRoute,
  } as any)
const ConnectedShellWorkflowsWorkflowIdRoute =
  ConnectedShellWorkflowsWorkflowIdRouteImport.update({
    id: '/$workflowId',
    path: '/$workflowId',
    getParentRoute: () => ConnectedShellWorkflowsRouteRoute,
  } as any)
const ConnectedShellSettingsPermissionProfilesIndexRoute =
  ConnectedShellSettingsPermissionProfilesIndexRouteImport.update({
    id: '/permission-profiles/',
    path: '/permission-profiles/',
    getParentRoute: () => ConnectedShellSettingsRouteRoute,
  } as any)
const ConnectedShellSettingsPermissionProfilesIdRoute =
  ConnectedShellSettingsPermissionProfilesIdRouteImport.update({
    id: '/permission-profiles/$id',
    path: '/permission-profiles/$id',
    getParentRoute: () => ConnectedShellSettingsRouteRoute,
  } as any)
const ConnectedShellThreadsSessionIdIndexRoute =
  ConnectedShellThreadsSessionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnectedShellThreadsSessionIdRouteRoute,
  } as any)
const ConnectedShellThreadsSessionIdSubagentsSubagentIdRoute =
  ConnectedShellThreadsSessionIdSubagentsSubagentIdRouteImport.update({
    id: '/subagents/$subagentId',
    path: '/subagents/$subagentId',
    getParentRoute: () => ConnectedShellThreadsSessionIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/first-run': typeof FirstRunRouteRoute
  '/': typeof ConnectedShellIndexRoute
  '/connect': typeof ConnectRoute
  '/login': typeof ConnectedLoginRoute
  '/settings': typeof ConnectedShellSettingsRouteRouteWithChildren
  '/workflows': typeof ConnectedShellWorkflowsRouteRouteWithChildren
  '/office': typeof ConnectedShellOfficeRoute
  '/settings/assistants': typeof ConnectedShellSettingsAssistantsRouteRoute
  '/threads/$sessionId': typeof ConnectedShellThreadsSessionIdRouteRouteWithChildren
  '/assistants/$assistantId': typeof ConnectedShellAssistantsAssistantIdRoute
  '/settings/appearance': typeof ConnectedShellSettingsAppearanceRoute
  '/settings/profile': typeof ConnectedShellSettingsProfileRoute
  '/settings/system': typeof ConnectedShellSettingsSystemRoute
  '/workflows/$workflowId': typeof ConnectedShellWorkflowsWorkflowIdRoute
  '/settings/': typeof ConnectedShellSettingsIndexRoute
  '/settings/permission-profiles/$id': typeof ConnectedShellSettingsPermissionProfilesIdRoute
  '/settings/permission-profiles/': typeof ConnectedShellSettingsPermissionProfilesIndexRoute
  '/threads/$sessionId/': typeof ConnectedShellThreadsSessionIdIndexRoute
  '/threads/$sessionId/subagents/$subagentId': typeof ConnectedShellThreadsSessionIdSubagentsSubagentIdRoute
}
export interface FileRoutesByTo {
  '/first-run': typeof FirstRunRouteRoute
  '/': typeof ConnectedShellIndexRoute
  '/connect': typeof ConnectRoute
  '/login': typeof ConnectedLoginRoute
  '/workflows': typeof ConnectedShellWorkflowsRouteRouteWithChildren
  '/office': typeof ConnectedShellOfficeRoute
  '/settings/assistants': typeof ConnectedShellSettingsAssistantsRouteRoute
  '/assistants/$assistantId': typeof ConnectedShellAssistantsAssistantIdRoute
  '/settings/appearance': typeof ConnectedShellSettingsAppearanceRoute
  '/settings/profile': typeof ConnectedShellSettingsProfileRoute
  '/settings/system': typeof ConnectedShellSettingsSystemRoute
  '/workflows/$workflowId': typeof ConnectedShellWorkflowsWorkflowIdRoute
  '/settings': typeof ConnectedShellSettingsIndexRoute
  '/settings/permission-profiles/$id': typeof ConnectedShellSettingsPermissionProfilesIdRoute
  '/settings/permission-profiles': typeof ConnectedShellSettingsPermissionProfilesIndexRoute
  '/threads/$sessionId': typeof ConnectedShellThreadsSessionIdIndexRoute
  '/threads/$sessionId/subagents/$subagentId': typeof ConnectedShellThreadsSessionIdSubagentsSubagentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/first-run': typeof FirstRunRouteRoute
  '/_connected': typeof ConnectedRouteWithChildren
  '/connect': typeof ConnectRoute
  '/_connected/_shell': typeof ConnectedShellRouteWithChildren
  '/_connected/login': typeof ConnectedLoginRoute
  '/_connected/_shell/settings': typeof ConnectedShellSettingsRouteRouteWithChildren
  '/_connected/_shell/workflows': typeof ConnectedShellWorkflowsRouteRouteWithChildren
  '/_connected/_shell/office': typeof ConnectedShellOfficeRoute
  '/_connected/_shell/': typeof ConnectedShellIndexRoute
  '/_connected/_shell/settings/assistants': typeof ConnectedShellSettingsAssistantsRouteRoute
  '/_connected/_shell/threads/$sessionId': typeof ConnectedShellThreadsSessionIdRouteRouteWithChildren
  '/_connected/_shell/assistants/$assistantId': typeof ConnectedShellAssistantsAssistantIdRoute
  '/_connected/_shell/settings/appearance': typeof ConnectedShellSettingsAppearanceRoute
  '/_connected/_shell/settings/profile': typeof ConnectedShellSettingsProfileRoute
  '/_connected/_shell/settings/system': typeof ConnectedShellSettingsSystemRoute
  '/_connected/_shell/workflows/$workflowId': typeof ConnectedShellWorkflowsWorkflowIdRoute
  '/_connected/_shell/settings/': typeof ConnectedShellSettingsIndexRoute
  '/_connected/_shell/settings/permission-profiles/$id': typeof ConnectedShellSettingsPermissionProfilesIdRoute
  '/_connected/_shell/settings/permission-profiles/': typeof ConnectedShellSettingsPermissionProfilesIndexRoute
  '/_connected/_shell/threads/$sessionId/': typeof ConnectedShellThreadsSessionIdIndexRoute
  '/_connected/_shell/threads/$sessionId/subagents/$subagentId': typeof ConnectedShellThreadsSessionIdSubagentsSubagentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/first-run'
    | '/'
    | '/connect'
    | '/login'
    | '/settings'
    | '/workflows'
    | '/office'
    | '/settings/assistants'
    | '/threads/$sessionId'
    | '/assistants/$assistantId'
    | '/settings/appearance'
    | '/settings/profile'
    | '/settings/system'
    | '/workflows/$workflowId'
    | '/settings/'
    | '/settings/permission-profiles/$id'
    | '/settings/permission-profiles/'
    | '/threads/$sessionId/'
    | '/threads/$sessionId/subagents/$subagentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/first-run'
    | '/'
    | '/connect'
    | '/login'
    | '/workflows'
    | '/office'
    | '/settings/assistants'
    | '/assistants/$assistantId'
    | '/settings/appearance'
    | '/settings/profile'
    | '/settings/system'
    | '/workflows/$workflowId'
    | '/settings'
    | '/settings/permission-profiles/$id'
    | '/settings/permission-profiles'
    | '/threads/$sessionId'
    | '/threads/$sessionId/subagents/$subagentId'
  id:
    | '__root__'
    | '/first-run'
    | '/_connected'
    | '/connect'
    | '/_connected/_shell'
    | '/_connected/login'
    | '/_connected/_shell/settings'
    | '/_connected/_shell/workflows'
    | '/_connected/_shell/office'
    | '/_connected/_shell/'
    | '/_connected/_shell/settings/assistants'
    | '/_connected/_shell/threads/$sessionId'
    | '/_connected/_shell/assistants/$assistantId'
    | '/_connected/_shell/settings/appearance'
    | '/_connected/_shell/settings/profile'
    | '/_connected/_shell/settings/system'
    | '/_connected/_shell/workflows/$workflowId'
    | '/_connected/_shell/settings/'
    | '/_connected/_shell/settings/permission-profiles/$id'
    | '/_connected/_shell/settings/permission-profiles/'
    | '/_connected/_shell/threads/$sessionId/'
    | '/_connected/_shell/threads/$sessionId/subagents/$subagentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FirstRunRouteRoute: typeof FirstRunRouteRoute
  ConnectedRoute: typeof ConnectedRouteWithChildren
  ConnectRoute: typeof ConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_connected': {
      id: '/_connected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConnectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-run': {
      id: '/first-run'
      path: '/first-run'
      fullPath: '/first-run'
      preLoaderRoute: typeof FirstRunRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_connected/_shell': {
      id: '/_connected/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConnectedShellRouteImport
      parentRoute: typeof ConnectedRoute
    }
    '/_connected/login': {
      id: '/_connected/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ConnectedLoginRouteImport
      parentRoute: typeof ConnectedRoute
    }
    '/_connected/_shell/': {
      id: '/_connected/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConnectedShellIndexRouteImport
      parentRoute: typeof ConnectedShellRoute
    }
    '/_connected/_shell/office': {
      id: '/_connected/_shell/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof ConnectedShellOfficeRouteImport
      parentRoute: typeof ConnectedShellRoute
    }
    '/_connected/_shell/settings': {
      id: '/_connected/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConnectedShellSettingsRouteRouteImport
      parentRoute: typeof ConnectedShellRoute
    }
    '/_connected/_shell/workflows': {
      id: '/_connected/_shell/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof ConnectedShellWorkflowsRouteRouteImport
      parentRoute: typeof ConnectedShellRoute
    }
    '/_connected/_shell/assistants/$assistantId': {
      id: '/_connected/_shell/assistants/$assistantId'
      path: '/assistants/$assistantId'
      fullPath: '/assistants/$assistantId'
      preLoaderRoute: typeof ConnectedShellAssistantsAssistantIdRouteImport
      parentRoute: typeof ConnectedShellRoute
    }
    '/_connected/_shell/settings/': {
      id: '/_connected/_shell/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ConnectedShellSettingsIndexRouteImport
      parentRoute: typeof ConnectedShellSettingsRouteRoute
    }
    '/_connected/_shell/settings/appearance': {
      id: '/_connected/_shell/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof ConnectedShellSettingsAppearanceRouteImport
      parentRoute: typeof ConnectedShellSettingsRouteRoute
    }
    '/_connected/_shell/settings/assistants': {
      id: '/_connected/_shell/settings/assistants'
      path: '/assistants'
      fullPath: '/settings/assistants'
      preLoaderRoute: typeof ConnectedShellSettingsAssistantsRouteRouteImport
      parentRoute: typeof ConnectedShellSettingsRouteRoute
    }
    '/_connected/_shell/settings/profile': {
      id: '/_connected/_shell/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ConnectedShellSettingsProfileRouteImport
      parentRoute: typeof ConnectedShellSettingsRouteRoute
    }
    '/_connected/_shell/settings/system': {
      id: '/_connected/_shell/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof ConnectedShellSettingsSystemRouteImport
      parentRoute: typeof ConnectedShellSettingsRouteRoute
    }
    '/_connected/_shell/threads/$sessionId': {
      id: '/_connected/_shell/threads/$sessionId'
      path: '/threads/$sessionId'
      fullPath: '/threads/$sessionId'
      preLoaderRoute: typeof ConnectedShellThreadsSessionIdRouteRouteImport
      parentRoute: typeof ConnectedShellRoute
    }
    '/_connected/_shell/workflows/$workflowId': {
      id: '/_connected/_shell/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof ConnectedShellWorkflowsWorkflowIdRouteImport
      parentRoute: typeof ConnectedShellWorkflowsRouteRoute
    }
    '/_connected/_shell/settings/permission-profiles/': {
      id: '/_connected/_shell/settings/permission-profiles/'
      path: '/permission-profiles'
      fullPath: '/settings/permission-profiles/'
      preLoaderRoute: typeof ConnectedShellSettingsPermissionProfilesIndexRouteImport
      parentRoute: typeof ConnectedShellSettingsRouteRoute
    }
    '/_connected/_shell/settings/permission-profiles/$id': {
      id: '/_connected/_shell/settings/permission-profiles/$id'
      path: '/permission-profiles/$id'
      fullPath: '/settings/permission-profiles/$id'
      preLoaderRoute: typeof ConnectedShellSettingsPermissionProfilesIdRouteImport
      parentRoute: typeof ConnectedShellSettingsRouteRoute
    }
    '/_connected/_shell/threads/$sessionId/': {
      id: '/_connected/_shell/threads/$sessionId/'
      path: '/'
      fullPath: '/threads/$sessionId/'
      preLoaderRoute: typeof ConnectedShellThreadsSessionIdIndexRouteImport
      parentRoute: typeof ConnectedShellThreadsSessionIdRouteRoute
    }
    '/_connected/_shell/threads/$sessionId/subagents/$subagentId': {
      id: '/_connected/_shell/threads/$sessionId/subagents/$subagentId'
      path: '/subagents/$subagentId'
      fullPath: '/threads/$sessionId/subagents/$subagentId'
      preLoaderRoute: typeof ConnectedShellThreadsSessionIdSubagentsSubagentIdRouteImport
      parentRoute: typeof ConnectedShellThreadsSessionIdRouteRoute
    }
  }
}

interface ConnectedShellSettingsRouteRouteChildren {
  ConnectedShellSettingsAssistantsRouteRoute: typeof ConnectedShellSettingsAssistantsRouteRoute
  ConnectedShellSettingsAppearanceRoute: typeof ConnectedShellSettingsAppearanceRoute
  ConnectedShellSettingsProfileRoute: typeof ConnectedShellSettingsProfileRoute
  ConnectedShellSettingsSystemRoute: typeof ConnectedShellSettingsSystemRoute
  ConnectedShellSettingsIndexRoute: typeof ConnectedShellSettingsIndexRoute
  ConnectedShellSettingsPermissionProfilesIdRoute: typeof ConnectedShellSettingsPermissionProfilesIdRoute
  ConnectedShellSettingsPermissionProfilesIndexRoute: typeof ConnectedShellSettingsPermissionProfilesIndexRoute
}

const ConnectedShellSettingsRouteRouteChildren: ConnectedShellSettingsRouteRouteChildren =
  {
    ConnectedShellSettingsAssistantsRouteRoute:
      ConnectedShellSettingsAssistantsRouteRoute,
    ConnectedShellSettingsAppearanceRoute:
      ConnectedShellSettingsAppearanceRoute,
    ConnectedShellSettingsProfileRoute: ConnectedShellSettingsProfileRoute,
    ConnectedShellSettingsSystemRoute: ConnectedShellSettingsSystemRoute,
    ConnectedShellSettingsIndexRoute: ConnectedShellSettingsIndexRoute,
    ConnectedShellSettingsPermissionProfilesIdRoute:
      ConnectedShellSettingsPermissionProfilesIdRoute,
    ConnectedShellSettingsPermissionProfilesIndexRoute:
      ConnectedShellSettingsPermissionProfilesIndexRoute,
  }

const ConnectedShellSettingsRouteRouteWithChildren =
  ConnectedShellSettingsRouteRoute._addFileChildren(
    ConnectedShellSettingsRouteRouteChildren,
  )

interface ConnectedShellWorkflowsRouteRouteChildren {
  ConnectedShellWorkflowsWorkflowIdRoute: typeof ConnectedShellWorkflowsWorkflowIdRoute
}

const ConnectedShellWorkflowsRouteRouteChildren: ConnectedShellWorkflowsRouteRouteChildren =
  {
    ConnectedShellWorkflowsWorkflowIdRoute:
      ConnectedShellWorkflowsWorkflowIdRoute,
  }

const ConnectedShellWorkflowsRouteRouteWithChildren =
  ConnectedShellWorkflowsRouteRoute._addFileChildren(
    ConnectedShellWorkflowsRouteRouteChildren,
  )

interface ConnectedShellThreadsSessionIdRouteRouteChildren {
  ConnectedShellThreadsSessionIdIndexRoute: typeof ConnectedShellThreadsSessionIdIndexRoute
  ConnectedShellThreadsSessionIdSubagentsSubagentIdRoute: typeof ConnectedShellThreadsSessionIdSubagentsSubagentIdRoute
}

const ConnectedShellThreadsSessionIdRouteRouteChildren: ConnectedShellThreadsSessionIdRouteRouteChildren =
  {
    ConnectedShellThreadsSessionIdIndexRoute:
      ConnectedShellThreadsSessionIdIndexRoute,
    ConnectedShellThreadsSessionIdSubagentsSubagentIdRoute:
      ConnectedShellThreadsSessionIdSubagentsSubagentIdRoute,
  }

const ConnectedShellThreadsSessionIdRouteRouteWithChildren =
  ConnectedShellThreadsSessionIdRouteRoute._addFileChildren(
    ConnectedShellThreadsSessionIdRouteRouteChildren,
  )

interface ConnectedShellRouteChildren {
  ConnectedShellSettingsRouteRoute: typeof ConnectedShellSettingsRouteRouteWithChildren
  ConnectedShellWorkflowsRouteRoute: typeof ConnectedShellWorkflowsRouteRouteWithChildren
  ConnectedShellOfficeRoute: typeof ConnectedShellOfficeRoute
  ConnectedShellIndexRoute: typeof ConnectedShellIndexRoute
  ConnectedShellThreadsSessionIdRouteRoute: typeof ConnectedShellThreadsSessionIdRouteRouteWithChildren
  ConnectedShellAssistantsAssistantIdRoute: typeof ConnectedShellAssistantsAssistantIdRoute
}

const ConnectedShellRouteChildren: ConnectedShellRouteChildren = {
  ConnectedShellSettingsRouteRoute:
    ConnectedShellSettingsRouteRouteWithChildren,
  ConnectedShellWorkflowsRouteRoute:
    ConnectedShellWorkflowsRouteRouteWithChildren,
  ConnectedShellOfficeRoute: ConnectedShellOfficeRoute,
  ConnectedShellIndexRoute: ConnectedShellIndexRoute,
  ConnectedShellThreadsSessionIdRouteRoute:
    ConnectedShellThreadsSessionIdRouteRouteWithChildren,
  ConnectedShellAssistantsAssistantIdRoute:
    ConnectedShellAssistantsAssistantIdRoute,
}

const ConnectedShellRouteWithChildren = ConnectedShellRoute._addFileChildren(
  ConnectedShellRouteChildren,
)

interface ConnectedRouteChildren {
  ConnectedShellRoute: typeof ConnectedShellRouteWithChildren
  ConnectedLoginRoute: typeof ConnectedLoginRoute
}

const ConnectedRouteChildren: ConnectedRouteChildren = {
  ConnectedShellRoute: ConnectedShellRouteWithChildren,
  ConnectedLoginRoute: ConnectedLoginRoute,
}

const ConnectedRouteWithChildren = ConnectedRoute._addFileChildren(
  ConnectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  FirstRunRouteRoute: FirstRunRouteRoute,
  ConnectedRoute: ConnectedRouteWithChildren,
  ConnectRoute: ConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
