#!/usr/bin/env bun
/**
 * Writes `apps/controller/src/http/bundle.ts`: one import per file of the web
 * bundle in `apps/web/dist`, which embeds the bundle in the binary.
 *
 * A compiled binary has no `dist/` on disk, so every file has to be named in
 * source before `bun build --compile` runs. `with { type: "file" }` embeds a
 * file: it makes the file part of the executable and gives the importer the
 * file's path inside it. Vite chooses the file names, including their content
 * hashes, so the list is generated after each `vite build` rather than
 * written by hand.
 *
 * Without `dist/`, the generated module exports no bundle, and the controller
 * serves the API alone. That is the state of a fresh checkout, which must typecheck
 * and test without anyone having run a web build.
 */
import { existsSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const dist = `${root}apps/web/dist`;
const module = `${root}apps/controller/src/http/bundle.ts`;

/** Every file under `dist/`, as the URL path a browser requests it at. */
const urlPaths = existsSync(dist)
  ? readdirSync(dist, { recursive: true, withFileTypes: true })
      .filter((entry) => entry.isFile())
      .map((entry) => `${entry.parentPath.slice(dist.length)}/${entry.name}`)
      .sort()
  : [];

const header = `/** Generated by scripts/gen-web-bundle.ts. Do not edit. */
// @ts-nocheck - the imports below resolve only once \`vite build\` has run.
import type { WebBundle } from "./static";
`;

if (urlPaths.length === 0) {
  await Bun.write(
    module,
    `${header}
export const webBundle: WebBundle | undefined = undefined;
`,
  );
  console.log("gen-web-bundle: no apps/web/dist; the controller will serve the API alone.");
} else {
  const buildImportName = (index: number): string => `file${String(index)}`;
  const imports = urlPaths
    .map(
      (path, index) =>
        `import ${buildImportName(index)} from "../../../web/dist${path}" with { type: "file" };`,
    )
    .join("\n");
  const entries = urlPaths
    .map((path, index) => `    [${JSON.stringify(path)}, ${buildImportName(index)}],`)
    .join("\n");
  const index = urlPaths.indexOf("/index.html");
  if (index === -1) throw new Error("apps/web/dist has no index.html");

  await Bun.write(
    module,
    `${header}${imports}

export const webBundle: WebBundle | undefined = {
  index: ${buildImportName(index)},
  files: new Map([
${entries}
  ]),
};
`,
  );
  console.log(`gen-web-bundle: embedded ${String(urlPaths.length)} files from apps/web/dist.`);
}
