/**
 * Write `packages/home/src/version.ts`.
 *
 * The version is baked in at build time: a compiled binary has no
 * `package.json` on disk to read. It is generated into
 * `@hydra/home` because that is the one leaf every role links: the dispatcher
 * prints it for `hydra --version` and the controller answers it from
 * `controller.read`, and neither may depend on the other.
 */
import { fileURLToPath } from "node:url";
import { $ } from "bun";

const root = fileURLToPath(new URL("..", import.meta.url));
const { version } = (await Bun.file(`${root}package.json`).json()) as { version: string };
const sha = (await $`git rev-parse --short HEAD`.cwd(root).nothrow().quiet().text()).trim();

await Bun.write(
  `${root}packages/home/src/version.ts`,
  `/** Generated by scripts/gen-version.ts. Do not edit. */
export const VERSION = ${JSON.stringify(sha ? `${version}+${sha}` : version)};
`,
);
