/**
 * Writes `packages/home/src/version.ts`.
 *
 * The version is baked in at build time: a compiled binary has no
 * `package.json` on disk to read. It is generated into
 * `@hercule/home` because that is the one package every role links and that
 * depends on nothing else: the dispatcher prints it for `hercule --version`
 * and the controller returns it from `controller.read`, and neither may
 * depend on the other.
 *
 * The Claude Code version is baked in next to it: the SDK works with the CLI
 * version it was built against and anything newer, so its own
 * `claudeCodeVersion` is the minimum version a machine must run. It is
 * recorded here and nowhere else.
 *
 * Codex has no SDK to read a version from, so its release is written here as a
 * literal: a devDependency on `@openai/codex` would pull a per-platform binary
 * into `node_modules` for one string. pi's release is a literal for the same
 * reason.
 */
import { fileURLToPath } from "node:url";
import { $ } from "bun";

/** The Codex release that this build's generated types and its installer both use. */
const CODEX_RELEASE = "0.154.0";

/**
 * The pi release this build's adapter was verified against. pi is pre-1.0 and
 * has broken its RPC mode between releases, so this is both the oldest version
 * a machine may run and the newest anyone has tested.
 */
const PI_RELEASE = "0.85.1";

const root = fileURLToPath(new URL("..", import.meta.url));
const { version } = (await Bun.file(`${root}package.json`).json()) as { version: string };
const sha = (await $`git rev-parse --short HEAD`.cwd(root).nothrow().quiet().text()).trim();
const { claudeCodeVersion } = (await Bun.file(
  `${root}apps/runner/node_modules/@anthropic-ai/claude-agent-sdk/package.json`,
).json()) as { claudeCodeVersion: string };

await Bun.write(
  `${root}packages/home/src/version.ts`,
  `/** Generated by scripts/gen-version.ts. Do not edit. */
export const VERSION = ${JSON.stringify(sha ? `${version}+${sha}` : version)};

/** The Claude Code CLI version the Agent SDK in this build was built against. */
export const CLAUDE_CODE_VERSION = ${JSON.stringify(claudeCodeVersion)};

/** The Codex release \`scripts/gen-codex-types.ts\` generated this build's types from. */
export const CODEX_VERSION = ${JSON.stringify(CODEX_RELEASE)};

/** The pi release this build's adapter was verified against. */
export const PI_VERSION = ${JSON.stringify(PI_RELEASE)};
`,
);
