/**
 * Write `packages/hydra/src/version.ts`.
 *
 * The version is baked in at build time: a compiled binary has no
 * `package.json` on disk to read (spec 15 section 11).
 */
import { $ } from "bun";

const root = new URL("..", import.meta.url).pathname;
const { version } = (await Bun.file(`${root}package.json`).json()) as { version: string };
const sha = (await $`git rev-parse --short HEAD`.cwd(root).nothrow().quiet().text()).trim();

const out = `${root}packages/hydra/src/version.ts`;
const body = `// Generated by scripts/gen-version.ts. Do not edit.
export const VERSION = ${JSON.stringify(sha ? `${version}+${sha}` : version)};
`;

const current = await Bun.file(out)
  .text()
  .catch(() => "");
if (current !== body) {
  await Bun.write(out, body);
}
